export const policies = [
  "account_number",
  "banking_information",
  "blood_type",
  "credit_card_cvv",
  "credit_card_expiration",
  "credit_card_number",
  "date",
  "date_of_birth",
  "drivers_license",
  "drug",
  "email_address",
  "event",
  "gender_sexuality",
  "healthcare_number",
  "injury",
  "ip_address",
  "language",
  "location",
  "medical_condition",
  "medical_process",
  "money_amount",
  "nationality",
  "number_sequence",
  "occupation",
  "organization",
  "passport_number",
  "password",
  "person_age",
  "person_name",
  "phone_number",
  "political_affiliation",
  "religion",
  "url",
  "us_social_security_number",
  "username",
  "vehicle_id",
] as const;

export const formattedPoliciesNotReadonly = [
  "Account Number",
  "Banking Information",
  "Blood Type",
  "Credit Card Cvv",
  "Credit Card Expiration",
  "Credit Card Number",
  "Date",
  "Date Of Birth",
  "Drivers License",
  "Drug",
  "Email Address",
  "Event",
  "Gender Sexuality",
  "Healthcare Number",
  "Injury",
  "Ip Address",
  "Language",
  "Location",
  "Medical Condition",
  "Medical Process",
  "Money Amount",
  "Nationality",
  "Number Sequence",
  "Occupation",
  "Organization",
  "Passport Number",
  "Password",
  "Person Age",
  "Person Name",
  "Phone Number",
  "Political Affiliation",
  "Religion",
  "Url",
  "Us Social Security Number",
  "Username",
  "Vehicle Id",
];

export const policy_descriptions = [
  "Customer account or membership identification number",
  "Banking information, including account and routing numbers",
  "Blood type",
  "Credit card verification code",
  "Expiration date of a credit card",
  "Credit card number",
  "Specific calendar date",
  "Date of birth",
  "Driver's license number.",
  "Medications, vitamins, or supplements",
  "Email address",
  "Name of an event or holiday",
  "Terms indicating gender identity or sexual orientation, including slang terms",
  "Healthcare numbers and health plan beneficiary numbers",
  "Bodily injury",
  "Internet IP address, including IPv4 and IPv6 formats",
  "Name of a natural language",
  "Any Location reference including mailing address, postal code, city, state, province, country, or coordinates.",
  "Name of a medical condition, disease, syndrome, deficit, or disorder",
  "Medical process, including treatments, procedures, and tests",
  "Name and/or amount of currency",
  "Terms indicating nationality, ethnicity, or race",
  "Numerical PII (including alphanumeric strings) that doesn't fall under other categories",
  "Job title or profession",
  "Name of an organization",
  "Passport numbers, issued by any country",
  "Account passwords, PINs, access keys, or verification answers",
  "Number associated with an age",
  "Name of a person",
  "Telephone or fax number",
  "Terms referring to a political party, movement, or ideology",
  "Terms indicating religious affiliation",
  "Internet addresses",
  "Social Security Number or equivalent",
  "Usernames, login names, or handles",
  "Vehicle identification numbers (VINs), vehicle serial numbers, and license plate numbers",
];
